apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talent-forge
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: talent-forge.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: talent-forge
                port:
                  number: 80
